"""empty message

Revision ID: 05e53d4b1c28
Revises: 61604e026da4
Create Date: 2022-09-22 21:21:58.655524

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05e53d4b1c28'
down_revision = '61604e026da4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inmueble', 'municipio')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inmueble', sa.Column('municipio', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
